'use client';
import { useEffect, useState } from 'react';
import type { ContactLeadRecord } from '../../../lib/content-db';

export default function SolicitudesPage() {
  const [leads, setLeads] = useState<ContactLeadRecord[]>([]);
  const [filter, setFilter] = useState<'new'|'contacted'>('new');
  const [loading, setLoading] = useState(true);
  useEffect(() => { fetch('/api/contact').then(response => response.ok ? response.json() : { leads: [] }).then(data => setLeads(data.leads ?? [])).finally(() => setLoading(false)); }, []);
  async function toggleStatus(id:number, status:'new'|'contacted') { const response = await fetch('/api/contact',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({id,status})}); if (response.ok) setLeads(current => current.map(lead => lead.id === id ? {...lead,status} : lead)); }
  const visible = leads.filter(lead => filter === 'contacted' ? lead.status === 'contacted' : lead.status !== 'contacted');
  return <main className="admin-shell"><aside className="admin-sidebar"><a className="brand" href="/"><span className="brand-name">valennet<small>content studio</small></span></a><nav><a href="/admin">Contenido</a><a className="active" href="/admin/solicitudes">Solicitudes <b className="admin-count">{leads.filter(lead=>lead.status!=='contacted').length}</b></a></nav><a className="admin-preview" href="/" target="_blank">Ver sitio ↗</a></aside><section className="admin-content requests-page"><header className="admin-header"><div><p>GESTIÓN DE CONTACTOS</p><h1>Solicitudes recibidas</h1><span className="requests-subtitle">Una bandeja simple para revisar, contactar y cerrar cada oportunidad.</span></div><a className="admin-back-link" href="/admin">← Volver al contenido</a></header><div className="lead-tabs"><button className={filter==='new'?'is-active':''} onClick={()=>setFilter('new')}>Pendientes ({leads.filter(lead=>lead.status!=='contacted').length})</button><button className={filter==='contacted'?'is-active':''} onClick={()=>setFilter('contacted')}>Contactados ({leads.filter(lead=>lead.status==='contacted').length})</button></div><div className="lead-table-wrap">{loading ? <p className="admin-empty">Cargando solicitudes…</p> : visible.length === 0 ? <p className="admin-empty">No hay solicitudes en esta bandeja.</p> : <table className="lead-table"><thead><tr><th>Fecha</th><th>Nombre / empresa</th><th>Servicio</th><th>Contacto</th><th>Mensaje</th><th>Acción</th></tr></thead><tbody>{visible.map(lead=><tr key={lead.id}><td>{new Date(lead.created_at).toLocaleDateString('es-PE')}</td><td><strong>{lead.name}</strong><small>{lead.company || 'Sin empresa'}</small></td><td><span className="lead-service">{lead.service}</span></td><td><a href={`mailto:${lead.email}`}>{lead.email}</a>{lead.phone && <a href={`tel:${lead.phone}`}>{lead.phone}</a>}</td><td className="lead-message-cell">{lead.message}</td><td><button className="lead-status-button" onClick={()=>toggleStatus(lead.id,lead.status==='contacted'?'new':'contacted')}>{lead.status==='contacted'?'Reabrir solicitud':'Marcar contactado'}</button></td></tr>)}</tbody></table>}</div></section></main>;
}
